import React from 'react';

import { storiesOf } from '@storybook/react';

import SVG from '../svg';

// I think this is the complete list of array object attributes to
// generate all necessary lines (values will need to be variables
// generated by user input):
// x1: '50',
// y1: '0',
// x2: '50',
// y2: '1000',
// strokeWidth: '1',
// stroke: 'black',
// transform: 'rotate(60,150,0)',
// strokeDasharray: '5',

const lineArray = [
  {
    x1: '50mm',
    y1: '0mm',
    x2: '50mm',
    y2: '1000mm',
    strokeWidth: '1',
    stroke: 'red',
    transform: 'rotate(60 50 0)',
  },
  // {
  //   x1: '100',
  //   y1: '0',
  //   x2: '100',
  //   y2: '1000',
  //   strokeWidth: '1',
  //   stroke: 'red',
  //   transform: 'rotate(60,100,0)',
  // },
  // {
  //   x1: '150',
  //   y1: '0',
  //   x2: '150',
  //   y2: '1000',
  //   strokeWidth: '1',
  //   stroke: 'red',
  //   transform: 'rotate(60,150,0)',
  // },
  // {
  //   x1: '50',
  //   y1: '0',
  //   x2: '50',
  //   y2: '1000',
  //   strokeWidth: '1',
  //   stroke: 'black',
    // transform: 'rotate(60,150,0)',
    // strokeDasharray: '5',
  // },
];

// Not sure how to structure this function for clean prop passing. Maybe it needs a `this` binding?
// lineArray.map(line =>
//   <line {...line} />);

class MySVG extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <SVG />
    );
  }
}

storiesOf('svg', module)
  .add('initial setup', () => (
    <SVG
      lineArray={lineArray}
    />
  ));
